### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './npy/XXXXX.npy'

### ISSUE THREAD

**Issue by sandy0427** [yongqyu/poi2vec#4]
I have downloaded your codes but missed several .npy files and  caused IOError. Would you please tell me what are the formats of train_xxx.npy and valid_xxx.npy so that I can revise the code and create them to run it? Thanks a lot.

**Comment by yongqyu** [comment]
Hello Sandy.
First of all, Im sorry for the delay in reply.

Since I did not write the README correctly, this problem seems to happen
frequently. I can not remember the old code I wrote.

Perhaps [ipyny / preprocess2.ipynb] (
https://github.com/yongqyu/poi2vec/blob/master/ipynb/preprocess2.ipynb)
will be the preprocessor file you were looking for.

Please check once.
Thank you.

2018년 10월 31일 (수) 오후 8:09, sandy0427 <notifications@github.com>님이 작성:
